const Joi = require('joi');

const id = Joi.number().integer().min(1);
const title = Joi.string().alphanum().min(3).max(255);
const artist_id = Joi.number().integer().min(10);

const createProductSchema = Joi.object({
  title: title.required(),
  artist_id: artist_id.required(),
});

const updateProductSchema = Joi.object({
  title: title,
  artist_id: artist_id,
});

const getProductSchema = Joi.object({
  id: id.required(),
});

module.exports = {
  createProductSchema,
  getProductSchema,
  updateProductSchema,
};

// const genre_id =;
// const stock = Joi.number().integer();
// const price = Joi.number().integer();
// const imagen = Joi.string();
// const created_at;


// "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
// "title" varchar(255) NOT NULL,
// "artist_id" integer NOT NULL,
// "genre_id" integer NOT NULL,
// "stock" integer NOT NULL,
// "price" DECIMAL(10,2) NOT NULL,
// "imagen" varchar,
// "created_at" timestamp DEFAULT 'now()'