services:
  postgres:
    image: postgres:16
    restart: always
    container_name: vinyl_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db_vinyl:/var/lib/postgres/data

volumes:
  db_vinyl:
